@base_url = {{dev_url}}

# @name Login

POST {{base_url}}/login
content-type: application/json

{
    "email": "john.doe@mediascout.co",
    "password": "password12345",
    "remember": true
}

### 

# @name SignUp