@base_url = {{dev_url}}

# @name Login

POST {{base_url}}/login
content-type: application/json
Accept: application/json

{
    "email": "john.doe@mediascout.co",
    "password": "password12345",
    "remember": true
}

### 

# @name SignUp

POST {{base_url}}/register
Content-Type: application/json
Accept: application/json

{
  "first_name": "Alex",
  "last_name": "Test",
  "email": "sania2403@gmail.com",
  "password": "tester123",
  "password_confirmation": "tester123"
}