@base_url = {{local_url}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbmlhMjQwM0BnbWFpbC5jb20iLCJuYW1lIjoiR3JheWNlIER1QnVxdWUiLCJpZCI6MTUsImlhdCI6MTU5MDA1NTMxNH0.fJ7bga4We3-Lj1RLUM_e7_vYMu8T6oJrZ4m6LZHAMkc

# @name Catalog
GET {{base_url}}/videos
Content-Type: application/json
Authorization: {{token}}

###

DELETE  {{base_url}}/videos/1
Content-Type: application/json
Authorization: {{token}}

###

GET  {{base_url}}/videos/66
Content-Type: application/json
Authorization: {{token}}

###

POST  {{base_url}}/videos
Content-Type: application/json
Authorization: {{token}}

{
  "link": "https://www.youtube.com/watch?v=IkgsUuFmqsQ"
}